spring.application.name=hms-auth

spring.datasource.url=jdbc:postgresql://localhost:5433/hms
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jooq.sql-dialect=postgres

server.port=8081

logging.level.org.springframework.security=TRACE

auth.client.id=hms-client
auth.client.secret=secret
auth.client.redirect-uri=http://localhost:8082/swagger-ui/oauth2-redirect.html

springdoc.swagger-ui.oauth.client-id=hms-client
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true

#logging.level.org.springframework.security.oauth2=TRACE
#logging.level.org.springframework.security.authorization=TRACE